/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package autoseater;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.Timeout;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.List;

import javax.security.auth.login.AppConfigurationEntry;

public class AppTest {
    @Rule
    public Timeout globalTimeout = Timeout.seconds(10);

    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void checkStudentList() {
        // App app = new App();

        List<Student> testStudentList = new ArrayList<Student>();

        for (int i = 0; i < 3; i++) {
            testStudentList.add(new Student(i, "Student " + i));
        }

        assertEquals(testStudentList.size(), 3);
    }

    @Test
    public void checkStudentId() {
        List<Student> testStudentList = new ArrayList<Student>();

        int testId;

        for (int i = 0; i < 3; i++) {
            testStudentList.add(new Student(i, "Student " + i));
        }

        testId = App.getStudentIdByName(testStudentList, testStudentList.get(2).getName());
        // testId = 2;

        System.out.println(testId);

        assertNotNull(testId);
    }

    @Test
    public void checkStudentName() {
        List<Student> testStudentList = new ArrayList<Student>();

        String testName;

        for (int i = 0; i < 3; i++) {
            testStudentList.add(new Student(i, "Student " + i));
        }

        testName = App.getStudentNameById(testStudentList, testStudentList.get(2).getIdNum());
        // testId = 2;

        System.out.println(testName);

        assertNotNull(testName);
    }
}
