/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package autoseater;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import javax.swing.plaf.basic.BasicInternalFrameTitlePane;

import org.chocosolver.solver.variables.IntVar;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int countStudent, countRows, countCols;
        IntVar[][] seats;
        List<Student> students = new ArrayList<>();
        // List<Integer[]> pairsForbidden = new ArrayList();
        // List<Integer[]> pairsAllowed = new ArrayList();

        Scanner scanner = new Scanner(System.in);
        // Assigner assigner = new Assigner();

        System.out.println("Enter the number of students: ");
        countStudent = scanner.nextInt();
        scanner.nextLine();

        // countRows = scanner.nextInt();
        // countCols = scanner.nextInt();

        for (int i = 0; i < countStudent; i++) {
            System.out.println("Enter name for Student " + i + ": ");
            String name = scanner.nextLine();
            students.add(new Student(i, name));
        }
        scanner.close();

        for (int j = 0; j < students.size(); j++) {
            System.out.println(students.get(j).getName());
        }

        // seats = assigner.assignSeats(countRows, countCols, pairsForbidden, pairsAllowed);
    }
}
